### ISSUE TITLE
Question: AngularJ-Universal limitations

### ISSUE THREAD

**Issue by danielGz** [swaechter/angularj-universal#14]
Does the library overcome the known limitations for Angular Universal like "no-DOM manipulation" ?

**Comment by swaechter** [comment]
Hey Daniel

Sorry for my late reply. Sadly no, all general limitations of Angular Universal apply because AngularJ Universal is using them under the hood:

- Never ever access the raw DOM like setting styles, installing listeners etc. Angular itself abstracts these manipulations and and provides the Renderer class https://angular.io/api/core/Renderer that provides a wrapper API and is also respected by server side rendering. The problem is, that third party libraries like jQuery/Other DOM libraries don't rely on this class --> Check if you are running on the server or client side via isBrowser/isNode
- No access to local storage

Of course you can replay the events via the Renderer and some custom code, but never access them before hand. Let's say a user has logged in to a website and stores his JWT access token in local storage (Which you shouldn't by the way), you will never be able to access this token on the server so easily (Of course with a lot of hacked JavaScript...but that won't work for all use cases).

You can find a pretty good article here. More or less all problems also apply for the Java abstraction: https://malcoded.com/posts/server-rendering-pitfalls
