### ISSUE TITLE
feature request: Add Lazy Loading module support

### ISSUE THREAD

**Issue by 4garfield** [swaechter/angularj-universal#16]
Hi, I'm using the `0.0.1` version with SpringBoot and it works fine.

But when I test the LayLoading module, the server side would generate additional "0.server.js", and it's would fail(V8 cannot find the `0.server.js` file). It's due to the `ResourceProvider` API only accept one `server.bundle.js` file, so I need manually copy the `0.server.js` to the temp folder.

so, can let the `ResourceProvider` constructor accept the server bundle folder ?

**Comment by swaechter** [comment]
Hey great to hear that :D

I had to change the provider API, means both provider are now merged and require the server bundle as file object. You can then decide if you want to listen to file changes and reload the engine automatically. Looks like I have to change that (Support directories).

I never worked with lazy loading for now, so is it possible for you to share a minimal working example, e.g create a repo and push your content? It can also be NodeJS based, but it would be good to have a minimalisitic one with as little boilerplate code as possible).

**Comment by swaechter** [comment]
I just added a working example with commit 97f0e56837d9e4148af8fc6c11447fe1c23190e9:

- On the server side, the whole application including all eager/lazy modules is just one single block
- On the client side, the application is loaded via code splitting

Note: `ng generate universal server` doesn't add the module `ModuleMapLoaderModule ` in `src/app/app.server.module.ts` - this has to be done manually. Otherwise you will receive some ngfactory error messages due the wrongly synced module map.
